#!/bin/bash

# if there are run dirs given use those
if [ $# -ne 0 ] ; then
    DIRS=$*
else
    DIRS=""
    for dia_filename in `find . -path "./data_*/DFM_OUTPUT*/flowfm*_0000.dia" -mmin -10` ; do
            RUN=`dirname $dia_filename`
	    RUN=`dirname $RUN`
            DIRS="$DIRS $RUN"
    done
fi

for RUN in $DIRS ; do
	echo $RUN
        dia_filename=$RUN/DFM_OUTPUT_flowfm/flowfm_0000.dia
	tail -5000 $dia_filename | grep % | tail -1 

	grep -l `basename $RUN`/ slurm*
	echo
done
